// Mocks generated by Mockito 5.4.4 from annotations
// in hamro_service/test/features/booking/presentation/providers/booking_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:hamro_service/core/error/failures.dart' as _i7;
import 'package:hamro_service/features/booking/data/models/booking_model.dart'
    as _i8;
import 'package:hamro_service/features/booking/domain/entities/service_option.dart'
    as _i5;
import 'package:hamro_service/features/booking/domain/entities/time_slot.dart'
    as _i6;
import 'package:hamro_service/features/booking/domain/repositories/booking_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingRepository extends _i1.Mock implements _i3.BookingRepository {
  MockBookingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ServiceOption>> getServiceOptions(
    String? serviceId,
    String? categoryTag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServiceOptions,
          [
            serviceId,
            categoryTag,
          ],
        ),
        returnValue:
            _i4.Future<List<_i5.ServiceOption>>.value(<_i5.ServiceOption>[]),
      ) as _i4.Future<List<_i5.ServiceOption>>);

  @override
  _i4.Future<List<_i6.TimeSlot>> getAvailableTimeSlots(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableTimeSlots,
          [date],
        ),
        returnValue: _i4.Future<List<_i6.TimeSlot>>.value(<_i6.TimeSlot>[]),
      ) as _i4.Future<List<_i6.TimeSlot>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, List<_i6.TimeSlot>>>
      getAvailableTimeSlotsFromAPI({
    required String? serviceId,
    required String? date,
    required String? area,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getAvailableTimeSlotsFromAPI,
              [],
              {
                #serviceId: serviceId,
                #date: date,
                #area: area,
              },
            ),
            returnValue:
                _i4.Future<_i2.Either<_i7.Failure, List<_i6.TimeSlot>>>.value(
                    _FakeEither_0<_i7.Failure, List<_i6.TimeSlot>>(
              this,
              Invocation.method(
                #getAvailableTimeSlotsFromAPI,
                [],
                {
                  #serviceId: serviceId,
                  #date: date,
                  #area: area,
                },
              ),
            )),
          ) as _i4.Future<_i2.Either<_i7.Failure, List<_i6.TimeSlot>>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> createBooking({
    required String serviceId,
    String? providerId,
    required String date,
    required String timeSlot,
    required String area,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBooking,
          [],
          {
            #serviceId: serviceId,
            #providerId: providerId,
            #date: date,
            #timeSlot: timeSlot,
            #area: area,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #createBooking,
            [],
            {
              #serviceId: serviceId,
              #providerId: providerId,
              #date: date,
              #timeSlot: timeSlot,
              #area: area,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>> getMyBookings(
          {String? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyBookings,
          [],
          {#status: status},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.BookingModel>>(
          this,
          Invocation.method(
            #getMyBookings,
            [],
            {#status: status},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> cancelBooking(
          String? bookingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelBooking,
          [bookingId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #cancelBooking,
            [bookingId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>>
      getProviderBookings({String? status}) => (super.noSuchMethod(
            Invocation.method(
              #getProviderBookings,
              [],
              {#status: status},
            ),
            returnValue: _i4
                .Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>>.value(
                _FakeEither_0<_i7.Failure, List<_i8.BookingModel>>(
              this,
              Invocation.method(
                #getProviderBookings,
                [],
                {#status: status},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i7.Failure, List<_i8.BookingModel>>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> acceptBooking(
          String? bookingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptBooking,
          [bookingId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #acceptBooking,
            [bookingId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> declineBooking(
          String? bookingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineBooking,
          [bookingId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #declineBooking,
            [bookingId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> completeBooking(
          String? bookingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeBooking,
          [bookingId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #completeBooking,
            [bookingId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> updateBookingStatus(
    String? bookingId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookingStatus,
          [
            bookingId,
            status,
          ],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #updateBookingStatus,
            [
              bookingId,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);

  @override
  _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>> updateBooking({
    required String? bookingId,
    String? date,
    String? timeSlot,
    String? area,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBooking,
          [],
          {
            #bookingId: bookingId,
            #date: date,
            #timeSlot: timeSlot,
            #area: area,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>.value(
                _FakeEither_0<_i7.Failure, _i8.BookingModel>(
          this,
          Invocation.method(
            #updateBooking,
            [],
            {
              #bookingId: bookingId,
              #date: date,
              #timeSlot: timeSlot,
              #area: area,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i7.Failure, _i8.BookingModel>>);
}
